---
- name: "Add repository key"
  apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present
  become: yes

- name: "Add repository"
  apt_repository: repo="deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" state=present
  become: yes

- name: "Install"
  apt: name="google-chrome-stable" update_cache=yes state=latest
  become: yes
